import "../styles/globals.css";
import Nav from "./components/nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by moi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Nav />
        <div className="m-2">{children}</div>
      </body>
    </html>
  );
}
